[package]
name = "chippers_rom_tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
modern = ["chippers_core/modern"]

[dependencies]
chippers_core = { path = "../core" }
